### ISSUE TITLE
Change Eslint camelCase rule to error

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#110]
- Change the eslint camelCase rule to be an error by default
- Add documentation about how to disable / ignore listing rules with comments

**Comment by brianjhanson** [comment]
[Documentation about configuring eslint with comments](https://eslint.org/docs/user-guide/configuring#configuring-rules)

**Comment by cmalven** [comment]
This should probably be here https://github.com/onedesign/eslint-config-odc/issues

**Comment by brianjhanson** [comment]
Yep, it should.

https://github.com/onedesign/eslint-config-odc/issues/19
