### ISSUE TITLE
Consider using yarn for install?

### ISSUE THREAD

**Issue by cmalven** [onedesign/generator-one-base#26]
I've been using `yarn` in place of `npm` for all new projects for awhile now. Anybody else jumped on this or having any feelings about starting to use `yarn` to install dependencies in this generator?

**Comment by brianjhanson** [comment]
I have it installed, but rarely use it. I'm not very clear / haven't seen a real benefit from it, but I'm not opposed to it.

**Comment by cmalven** [comment]
The only direct benefit I experience from it is that things install significantly faster, and the more you use it, the more difference that makes (because the similar packages you use between projects are cached and install insanely fast).

The indirect benefit that doesn't come up often, but when it has come up has been a huge pain, is consistent builds. With yarn you get 100% repeatable installs from machine to machine. With npm you may or may not get that.

I don't feel strongly about it, just seeing if anyone else was using it.

**Comment by brianjhanson** [comment]
I'm down for it. My big hold up was no yeoman support, but it appears that that has changed https://github.com/yeoman/generator/issues/964

**Comment by cmalven** [comment]
Closed by #29
