### ISSUE TITLE
Add gulp to package.json

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#38]
A downside of our new, fancy `yarn run` is that we don't currently install gulp in the package.json

**Comment by cmalven** [comment]
We don't? Then how is it working for me right now without `gulp-cli` installed globally?

**Comment by cmalven** [comment]
https://github.com/onedesign/generator-one-base/blob/master/generators/gulp/index.js#L56

**Comment by brianjhanson** [comment]
I'm actually not sure, I just ran it, and it didn't seem to install _any_ dependencies. So I'm not sure what happened. I'm guessing a choice I made led to a bit of a bug.

**Comment by cmalven** [comment]
Check the logs during the install. I found yesterday that the install was failing early on causing the rest of the installs to fail. Ended up being because `yarn install` _always_ uses your system node, which may cause some issues if its too old (mine was).

**Comment by cmalven** [comment]
@brianjhanson did you ever figure out what was causing this?

**Comment by brianjhanson** [comment]
Nope, I'm going to call it user error though.
