### ISSUE TITLE
Allow generator to run in current directory

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#43]
Right now we create a folder _within_ the current directory, but it would also be useful to allow you to output all this stuff in whatever directory you're in.

**Comment by cmalven** [comment]
@brianjhanson what's your use case for this? Seems like the downside to creating a sub-directory would only be you have to copy files out of it and delete it, but the downside of accidentally putting things in the current directory when you didn't mean to is anything from chaos to lost files.

**Comment by brianjhanson** [comment]
I mostly want to be able to port these updates over to an existing project. So, for example, if I wanted to bring Optimas in line with our current standards running the generator (or something) to do that would be awesome. 

As a side note, it would be great to be able to run it in order to create gulp tasks. Like if I didn't think I'd need SVG and then I end up needing it later.

**Comment by cmalven** [comment]
Okay, I gotcha. The tricky part is that Yeoman can't handle file collisions very well at all, so there's really no elegant way to say "this file might exist but just overwrite it". You have to manually account for all of the possible file collisions that could happen.

**Comment by cmalven** [comment]
> As a side note, it would be great to be able to run it in order to create gulp tasks. Like if I didn't think I'd need SVG and then I end up needing it later.

We could probably handle this by creating sub-generators for each gulp task, so you'd do `yo one-base:gulp svg` for instance and it would add just the `svg.js` file to the appropriate place and `yarn add` the necessary files. Still not trivial but easier to handle.

**Comment by cmalven** [comment]
After doing some reading, I think I have an idea about how we might accomplish this.

First we would add a `--current-dir` command line flag that would say "do everything in the current directory instead of a new directory. This alone would be almost enough to accomplish this, but Yeoman would still ask you to confirm the overwrite of every single file which could be annoying. Using the `--force` flag in addition forces any existing files to be overwritten.

So the end use would be `yo one-base --current-dir --force`

**Comment by brianjhanson** [comment]
StudioNY107 just implemented something similar to this for their plugin factory generator. It looks like his solution was to create a dotfile in the root that stores the current state. This allows you to append rather than overwrite. I think ideally we would split this generator into a bunch of smaller tasks so we could add them on the fly (which is what I was trying to get at in my original issue). 

I'd love to get to a place where we can do something like 
`yo one-base --gulp-task images` to scaffold out our standard image task.

here's a little video that explains it https://youtu.be/K-PwDHS76So

**Comment by cmalven** [comment]
I agree with you that a bunch of smaller, ideally completely decoupled tasks, would be great. The thing that makes this so hard is that modifying existing text files is very difficult and fraught with peril. The official Yeoman docs warn against even trying to do it (which seems unrealistic but I think speaks to how hard it is to do well). 

Even something as simple as adding an additional line to our `.gitignore` or adding an addition task to the default gulp task requires reading in the file, parsing it very carefully, modifying it, and saving the file back out again.

I'd guess the reason its not a big deal for `generator-craft-plugin` is that he's either not modifying existing text files, or doing so very rarely.

That being said, actually creating the gulp tasks in the right place would be pretty easy. It's the modification of any existing files needed to support them is the tricky part.

**Comment by cmalven** [comment]
This has been tackled specifically for the `gulp` sub-generator in #74 

It _does not_ implement the installing of individual gulp tasks through the generator, but I welcome someone else to take that on.
