### ISSUE TITLE
Add .htaccess file to craft generator

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#46]
Didn't realize this was missing until @MikeMcChillin tried to get a project built with this up and running.

**Comment by cmalven** [comment]
Good catch. Could've sworn that was in there, but we must be completely wiping out Craft's default `/public` directory.

**Comment by cmalven** [comment]
According to my latest run of the generator (and my past experience) we shouldn't need to manually copy over an htaccess template, because we don't delete the one that Craft comes with.

**Comment by cmalven** [comment]
You _do_ however, need to manually rename `htaccess` to `.htaccess`, just like you've always had to do with Craft, so make sure you're doing that.

**Comment by brianjhanson** [comment]
Looks like a combo of things. I forgot to rename it to .htaccess, but also our `.gitignore` is ignoring it by default.

https://github.com/onedesign/generator-one-base/blob/master/generators/app/templates/.gitignore#L31

**Comment by cmalven** [comment]
Did we explicitly decide to ignore it, or did it slip through the cracks when we added `public/*`?
