### ISSUE TITLE
Remove duplicate helpers

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#51]
Just realized we have both a `helpers/` folder as well as a `base/_helpers.scss` file. I feel like we should go one way or the other.

**Comment by cmalven** [comment]
Yep, I agree. You have a strong opinion on this? I think I could go either way.

**Comment by brianjhanson** [comment]
I would vote for the `base/_helpers` file since most of them are one-liners. Seems silly to put them in their own file.
