### ISSUE TITLE
Add craft storage folder

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#63]
Right now Craft gets all mad because it's not there by default.

**Comment by cmalven** [comment]
Just FYI, because the storage folder is empty by default you'll need to a `.gitignore` to it (or a similar solution) to make sure it is stored in version control.

**Comment by mkornatz** [comment]
FYI, `.gitkeep` files are used for this purpose

**Comment by molwells** [comment]
Reopening - I just ran into this issue last week.

**Comment by cmalven** [comment]
@molwells have you pulled the latest generator locally?

**Comment by cmalven** [comment]
@molwells I ask because this should've been fixed by https://github.com/onedesign/generator-one-base/commit/4b44da336ba40b140ea9f88e4c6b319a9221d1b7

**Comment by molwells** [comment]
@cmalven Good call. I _think_ I pulled the latest, but let me double check.

**Comment by molwells** [comment]
@cmalven You are correct, it's fixed. Closing this issue (again).
