### ISSUE TITLE
Over ignoring plugins

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#65]
Right now we're ignoring everything in `craft/plugins` which is great, but if you choose to install plugins then running for the first time those also get ignored. 

We should update the `.gitignore` based on your plugin choices.

**Comment by cmalven** [comment]
I think only a couple plugins right now are installed outside of composer, and that number will go down in the future, but I generally agree. It's just that it's really hard/gross to modify a generated text file after it is created, and I couldn't come up with another way to make this happen (if I'm remember correctly).

**Comment by mkornatz** [comment]
What about including a `.gitignore` file in `craft/plugins/` that's customizable? Does that make things a little cleaner?

**Comment by cmalven** [comment]
I think the issue _was_ the order of creation (the `.gitignore` is technically created before the Craft sub-generator creation step occurs, so it doesn't get a chance to modify that file). So if we created that plugin `.gitignore` as a part of the Craft sub-generator, it would sidestep that issue and make it pretty easy. It would require the user to be aware that they had to handle plugin ignores in a separate place, but it would be the easiest way to accomplish this I think.

**Comment by cmalven** [comment]
We could fix this, but when Craft 3 comes out all plugins are going to require composer so it will be a moot issue. Just sayin'.

**Comment by brianjhanson** [comment]
Yeah, I would say this isn't a large enough problem to warrant fixing with Craft 3 (sort of) looming.

**Comment by cmalven** [comment]
Resolved-ish by Craft 3, and no simple fix for Craft 2, so closing.
