### ISSUE TITLE
Make linting errors less ignorable

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#67]
I feel like I opened this before, but either way. 

Right now it's super easy to ignore linting errors, we should make those harder to ignore. I did something like this on JLLIPT where the errors were injected into the page as HTML markup. It worked pretty well as far as the "not ignoring" them goes.

**Comment by cmalven** [comment]
I agree, but I'm also not sure of the best way to solve it. Ideally, it would hook into the same browsersync-based notifications system that we currently use to display JS/CSS compilation errors in the browser, but the tricky part is making sure that they both show up, or at the very least that displaying compilation errors takes precedence over displaying linting errors.
