### ISSUE TITLE
Remove Craft Options

### ISSUE THREAD

**Issue by brianjhanson** [onedesign/generator-one-base#68]
I know we _just_ added this, but with Craft 3 around the corner the Craft install part of this will become less useful. I'm wondering if this generator should only be concerned about front end stuff, meaning it would scaffold out our directory structure, gulp tasks, etc. but be BYO back end solution. 

Just a thought, but it would simplify things, and make it easier to include this on non-craft projects.

**Comment by cmalven** [comment]
What problems have you had using it on non-craft projects? I've used it on several frontend-only projects without a problem. If you select `Static` for the platform when running it, not a single craft-related thing will be added.

I also don't think Craft 3 is going to change much of the usefulness of it. Craft 3 won't handle the plugins that get installed, or the default config options, or the gitignore/htaccess, or the default templates, or the directory structure, or the directory permissions. The _only_ thing that Craft 3 will change is that we can install Craft itself and all plugins using Composer, whereas right now we have to install Craft with a manual download request and some plugins as well.

Given that the majority of the time this gets used is probably on a Craft project, and that (in my experience) it can be used for non-craft projects with no problem, I don't totally understand the desire to eliminate it.

**Comment by cmalven** [comment]
I think the solution to this is to refactor the sub-generators to be less coupled, which is started with #74

The base generator is already pretty decoupled from Craft if you set the `platform` to `Static` when running the generator.
