### ISSUE TITLE
Add conditionals in gulp config to check for .env file

### ISSUE THREAD

**Issue by molwells** [onedesign/generator-one-base#80]
When using the generator to create a static (not Craft) site, it doesn't output a `.env` file. That's great, except our gulp `config.js` still tries to load the `.env` to use it's value for the `proxyUrl` prop.

**Comment by cmalven** [comment]
Oops. Yep that must've slipped through the cracks on #79 

We'll need to output the `.env` file as part of the base generator in addition to (or instead of) outputting it as part of the Craft sub-generator.
