### ISSUE TITLE
Add dotenv to package.json

### ISSUE THREAD

**Issue by molwells** [onedesign/generator-one-base#81]
Our `gulp/config.js` requires `dotenv`, but that package does not exist in our `package.json`

**Comment by cmalven** [comment]
@molwells This one should be pretty simple. Do you have any interest in tackling this?

It would be as simple as adding `dotenv` to the list here https://github.com/onedesign/generator-one-base/blob/master/generators/gulp/index.js#L43

**Comment by molwells** [comment]
@cmalven I do! I'll let you know if I have any questions.

**Comment by cmalven** [comment]
Great! Thanks @molwells!

**Comment by cmalven** [comment]
@molwells not sure how I didn't notice this earlier, but it _does_ look like `dotenv` is getting installed and should be in the `package.json` (https://github.com/onedesign/generator-one-base/blob/master/generators/gulp/index.js#L53). And then I double-checked by running the generator and `dotenv` is indeed in my package.json. Can you make sure your generator is up-to-date and try again?

**Comment by molwells** [comment]
Ah @cmalven my bad. I didn't setup the project where I noticed this bug, and I had (wrongly) assumed the project was created using the latest version of the generator. Closing this issue.

**Comment by cmalven** [comment]
Phew! Thanks for double-checking @molwells
