### ISSUE TITLE
Robots.txt in /public folder

### ISSUE THREAD

**Issue by MikeMcChillin** [onedesign/generator-one-base#89]
The `robots.txt` file in `/public` overwrites SEOmatic's robots config.
Should we eliminate it from this generator since we use SEOMatic on all our craft sites?

**Comment by cmalven** [comment]
If you've chosen to install `seomatic` during the generator prompts, we'll automatically remove the default `robots.txt` (and you'll see a message that we removed it)

https://github.com/onedesign/generator-one-base/blob/master/generators/craft/index.js#L53

If you're still seeing this you may need to pull down the latest generator.

**Comment by MikeMcChillin** [comment]
Ah, it's entirely possible that step was skipped. If this has already been considered / works like you said, feel free to close this issue.
