### ISSUE TITLE
Update Normalize.css

### ISSUE THREAD

**Issue by MikeMcChillin** [onedesign/generator-one-base#94]
Normalize.css is on version 7.00 now.
The one included here is pretty old & I just ran into a weird `box-sizing` issue: 
https://github.com/onedesign/generator-one-base/blob/master/generators/app/templates/src/styles/vendor/_normalize.scss#L357

Should we update the version? Or maybe install via `npm`?

**Comment by cmalven** [comment]
Yeah, we should do something about this. My preference for things like Normalize is to update our built in version so we don't inadvertently have things change mysteriously between projects, but I'm cool with either.
